# Generated by Django 3.1.4 on 2021-01-23 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoDars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('rasm', models.ImageField(upload_to='video_daraslar/rasmlar')),
                ('izox', models.TextField()),
                ('video', models.FileField(upload_to='video_darslar/video')),
                ('playlisti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.playlist')),
            ],
        ),
    ]
