# Generated by Django 3.1.4 on 2021-01-23 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0002_videodars'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodars',
            name='sana',
            field=models.DateField(auto_now_add=True, default=0),
            preserve_default=False,
        ),
    ]
